#+TITLE: Algorytmy i Struktury Danych
#+AUTHOR: Mateusz Słodkowicz
#+OPTIONS: \n:t
#+LANGUAGE: pl
#+EXPORT_FILE_NAME: ../Algorytmy i struktury danych/README.md
#+PANDOC_OPTIONS: lua-filter:fix.lua

Zadania/Ćwiczenia z przedmiotu Algorytmy i Struktury Danych.
* Ćwiczenie 2 - Zadanie 1
Program na rozwiązywanie równania kwadratowego.

*Wymagania na program*:
1. Aplikacja konsolowa (prosty program)
2. Na wejściu programu należy podać wartości a,b,c
3. Na wyjściu program wypisuje komunikaty, opisane algorytmem

[[./Pascal/AiSD5_C2 Ćwiczenie 2/zad1_rownanie_kwadratowe.pas][Pascal]] [[./Python/AiSD5_C2 Ćwiczenie 2/zad1_rownanie_kwadratowe.py][Python]]

* Ćwiczenie 2 - Zadanie 2
*Definicja*
Rok przestępny to taki, który spełnia następujące warunki:
 - jest podzielny przez 4 i niepodzielny przez 100
lub
 - jest podzielny przez 400
*Wymagania na program*:
1. Aplikacja konsolowa (prosty program)
2. Na wejściu programu należy podać liczbę określającą numer roku
3. Na wyjściu program wypisuje komunikat, czy podany rok jest przestępny.
4. Podziel program na cztery części:
  1) Funkcja typu całkowitego czytająca numer roku podany przez użytkownika i zwracająca odczytaną liczbę
  2) Funkcja typu logicznego, której argumentem jest liczba całkowita sprawdzająca, czy rok jest przestępny
  3) Procedura, której argumentami są: numer roku i wartość logiczna, wypisująca na konsoli, czy rok jest przestępny
  4) Procedura zawierająca w sobie wywołania pozostałych funkcji i procedur, która jest wywoływana z programu głównego.

[[./Pascal/AiSD5_C2 Ćwiczenie 2/zad2_rok_przestepny.pas][Pascal]] [[./Python/AiSD5_C2 Ćwiczenie 2/zad2_rok_przestepny.py][Python]]

* Ćwiczenie 2 - Zadanie 3
Obliczanie sumy cyfr

*Wymagania na algorytm*:
1. Algorytm iteracyjny (nie rekurencyjny)

*Wymagania na program*:
1. Aplikacja konsolowa (prosty program)
2. Na wejściu programu należy podać liczbę całkowitą.
3. Na wyjściu program wypisuje wynik obliczeń.
4. Podziel program na cztery części:
  1) Funkcja typu całkowitego czytająca liczbę całkowitą
  2) Funkcja typu całkowitego, której argumentem jest liczba całkowita, a wynikiem suma cyfr tej liczby
  3) Procedura wypisująca wynik obliczeń, której argumentami są: liczba całkowita i suma cyfr tej liczby
  4) Procedura zawierająca w sobie wywołania pozostałych funkcji i procedur, która jest wywoływana z programu głównego.

[[./Pascal/AiSD5_C2 Ćwiczenie 2/zad3_suma_cyfr.pas][Pascal]] [[./Python/AiSD5_C2 Ćwiczenie 2/zad3_suma_cyfr.py][Python]]
